sudo: false
language: php
php:
- '5.6'
- '5.5'
- '5.4'

before_install:
  - git clone https://github.com/squizlabs/PHP_CodeSniffer.git phpcs
  - git clone -b master https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wpcs
  - ./phpcs/scripts/phpcs --config-set installed_paths ../wpcs

script:
  - ./phpcs/scripts/phpcs --standard=ruleset.xml --extensions=php -n -s src
